#!/bin/bash

echo
echo
echo ">>>>>>>>>>>>>>>>>>>>>>>>> Repository builder start >>>>>>>>>>>>>>>>>>>>>>>>>"
echo "Build Repository for external use"

GROUP=$1
MODULE=$2
VERSION=$3

echo "Working path is:"
pwd

echo "Handling module '$MODULE' of group '$GROUP', version='$VERSION'"

/usr/bin/mvn install:install-file -DgroupId=$GROUP -DartifactId=$MODULE -Dversion=1.0 -Dfile=CMpub/jars/$MODULE-$VERSION.jar -Dpackaging=jar -DgeneratePom=true -DlocalRepositoryPath=repo  -DcreateChecksum=true

echo "<<<<<<<<<<<<<<<<<<<<<<<<< Repository builder finish <<<<<<<<<<<<<<<<<<<<<<<<<"
echo
echo

